<?php

use Illuminate\Foundation\Application;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));
// define start time, Laravel measures how long the request takes.

// Determine if the application is in maintenance mode...
if (file_exists($maintenance = __DIR__ . '/../storage/framework/maintenance.php')) {
    require $maintenance;
}
//If the site is in maintenance mode (php artisan down), it returns that page.

require __DIR__ . '/../vendor/autoload.php';
// This file is generated by Composer and makes all your classes (controllers, models, facades, etc.) automatically loadable.

/** @var Application $app */
$app = require_once __DIR__ . '/../bootstrap/app.php';
// This creates a new Application container and configures routes, middleware, and services — based on what you defined in bootstrap/app.php.

$app->handleRequest(Request::capture());
// This line actually:
// Captures the incoming HTTP request
// Passes it to the Laravel kernel
// Resolves the correct route/controller
// Returns the final response (JSON, HTML, etc.)